export const SET_SEARCH_TERM_ACTION = 'SET_SEARCH_TERM_ACTION'
export const SET_EVENTS_ACTION = 'SET_EVENTS_ACTION'
export const SET_ERROR_ACTION = 'SET_ERROR_ACTION'
export const SET_LOADING_ACTION = 'SET_LOADING_ACTION'